[{$smarty.block.parent}]
[{assign var=jsAssets value=$oViewConf->getWebpackJavascriptFiles('main')}]
[{foreach $jsAssets as $asset}]
    [{oxscript include=$asset}]
[{/foreach}]

[{assign var=jsAssets value=$oViewConf->getWebpackJavascriptFiles()}]
[{foreach $jsAssets as $asset}]
    [{oxscript include=$asset}]
[{/foreach}]