[{$smarty.block.parent}]
[{assign var=jsAssets value=$oViewConf->getWebpackCSSFiles('main')}]
[{foreach from=$jsAssets item=asset}]
    [{oxstyle include=$asset|ltrim:'/' priority=1}]
[{/foreach}]

[{assign var=jsAssets value=$oViewConf->getWebpackCSSFiles()}]
[{foreach from=$jsAssets item=asset}]
    [{oxstyle include=$asset|ltrim:'/'}]
[{/foreach}]

[{assign var=preloadAssets value=$oViewConf->getPreloadAssets()}]
[{foreach from=$preloadAssets item=asset}]
    [{oxeval var=$asset force=true}]
[{/foreach}]